# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
name: TodoApp CI

on:
  push:
    branches: master

jobs:
  backend:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: backend/package-lock.json
      - run: npm ci
      - run: npm test
#       - run: npm run build --if-present
#       - uses: akhileshns/heroku-deploy@v3.12.12
#         with:
#           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#           heroku_app_name: "ease-app"
#           heroku_email: "vickylam780@gmail.com"
  
  frontend:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: frontend

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
